### ISSUE TITLE
Kp5L bltouch fails to deploy

### ISSUE THREAD

**Issue by caseystarr** [nehilo/Klipper-KingRoon-Printers#12]
Kp5L bltouch fails to deploy. Bltouch is a 3dtouch provided by kingroon and I followed instructions on their site to wire the probe.

**Comment by Coblenugget** [comment]
I am also having this issue

**Comment by nehilo** [comment]
Use pin Z-

**Comment by caseystarr** [comment]
The Z- does not work

**Comment by nehilo** [comment]
> The Z- does not work

Chk connection by multimeter
