### ISSUE TITLE
Can we have a license for this repo

### ISSUE THREAD

**Issue by chaopeng** [nehilo/Klipper-KingRoon-Printers#16]
I would like to fork this repo and add some change based on my printer. Then I found this is a no license repo, it makes others hard to work on / share / use this "legally". Could you please add a LICENSE for this repo. It would be good if it is BSD or Apache2. Thank you.

**Comment by nehilo** [comment]
This is not licensed repo
Base on Klipper official doc
You can use it you own risk and forked it
