### ISSUE TITLE
BLTOUCH is always giving me an open state

### ISSUE THREAD

**Issue by Coblenugget** [nehilo/Klipper-KingRoon-Printers#18]
I have made sure that the wiring is correct and I have it plugged into z- where the z endstop use to be at. I have tried different cables and a clone with the same results

[bltouch]
sensor_pin: ^PA11
control_pin: PA8
speed: 20
x_offset: -25
y_offset: -28
z_offset: 1.099
pin_move_time: 0.400
probe_with_touch_mode: False
pin_up_reports_not_triggered: True
pin_up_touch_mode_reports_triggered: True
lift_speed: 15
samples: 2
sample_retract_dist: 5.0
samples_tolerance: 0.05
samples_tolerance_retries: 5

[safe_z_home]
home_xy_position: 188,181
speed: 50
z_hop: 8
z_hop_speed: 25

![PXL_20221231_044438913](https://user-images.githubusercontent.com/61342259/210125224-ce45f7fe-a781-41ac-94bd-a63aff1527b7.jpg)
![PXL_20221231_044447769](https://user-images.githubusercontent.com/61342259/210125227-ffc4020f-f850-40e6-849b-fa0bafc9c6fa.jpg)

**Comment by wonsnot** [comment]
I have the same issue with both a 3d touch from klipper and with an official bltouch.

**Comment by wxt203814** [comment]
the hashtag is what made mine work infront of the " probe_touch_mode" argument 



[bltouch]
sensor_pin: ^PA11
control_pin: PA8
speed: 20
x_offset: -25
y_offset: -28
z_offset: 1.099
pin_move_time: 0.400
#probe_with_touch_mode: True # for original BLTouch v 3.0
pin_up_reports_not_triggered: True
pin_up_touch_mode_reports_triggered: True
lift_speed: 15
samples: 2
sample_retract_dist: 5.0
samples_tolerance: 0.05
samples_tolerance_retries: 5

**Comment by nehilo** [comment]
> the hashtag is what made mine work infront of the " probe_touch_mode" argument
> 
> [bltouch] sensor_pin: ^PA11 control_pin: PA8 speed: 20 x_offset: -25 y_offset: -28 z_offset: 1.099 pin_move_time: 0.400 #probe_with_touch_mode: True # for original BLTouch v 3.0 pin_up_reports_not_triggered: True pin_up_touch_mode_reports_triggered: True lift_speed: 15 samples: 2 sample_retract_dist: 5.0 samples_tolerance: 0.05 samples_tolerance_retries: 5

"probe_touch_mode" argument need for another bltouch clone. Some of it work without "probe_touch_mode"
